name: Welingkar Timetable Bot

on:
  workflow_dispatch:

  schedule:
    - cron: "2-59/5 * * * *"

concurrency:
  group: timetable-bot
  cancel-in-progress: true

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: |
          playwright install --with-deps chromium

      - name: Run timetable bot
        env:
          WEWORLD_USERNAME: ${{ secrets.WEWORLD_USERNAME }}
          WEWORLD_PASSWORD: ${{ secrets.WEWORLD_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot.py
